version: "3.9"
services:
  scraiper:
    build:
      context: ./scraiper
    deploy:
      resources:
        limits:
          memory: 4096M
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    image: scraiper
    restart: unless-stopped
    networks:
      - scrapenet
    cap_drop:
      - ALL
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-behnoush}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-tolls}
    env_file: .env
    volumes:
      - ./scraiper/csvs:/csvs:ro
    command: ["--csv", "/csvs/road_tolls.csv"]
  scraiper_api:
    build:
      context: ./scraiper_api
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    image: scraiper_api
    restart: unless-stopped
    ports:
      - "[::1]:8008:8000/tcp"
    networks:
      - apinet
    cap_drop:
      - ALL
    env_file: .env
    # entrypoint: ["/docker-entrypoint.sh"]
  postgres:
    image: postgres:16-alpine3.18
    deploy:
      resources:
        limits:
          memory: 4096M
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    ports:
      - "[::1]:5422:5432/tcp"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-behnoush}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-tolls}
    env_file: .env
    volumes:
      - postgres-vault:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    networks:
      - scrapenet
      - dbnet
      - apinet
  pgadmin:
    image: dpage/pgadmin4:7.8
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    environment:
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT:-5050}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-devi@terminaldweller.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-changeme}
      - PGADMIN_DISABLE_POSTFIX=${PGADMIN_DISABLE_POSTFIX:-YES}
    env_file: .env
    ports:
      - "[::1]:5050:5050/tcp"
    restart: unless-stopped
    volumes:
      - pgadmin-vault:/var/lib/pgadmin
    networks:
      - dbnet
volumes:
  postgres-vault:
  pgadmin-vault:
networks:
  scrapenet:
  dbnet:
  apinet:
